language: node_js

node_js:
   - "stable"

before_script:
    - npm install
    - npm install -g codecov

script:
    - npm run test

after_script:
    - npm run coveralls
    - npm run coverage
    - codecov
